!function(e,t){e&&!e.getElementById("livereloadscript")&&((t=e.createElement("script")).async=1,t.src="//"+(self.location.host||"localhost").split(":")[0]+":35729/livereload.js?snipver=1",t.id="livereloadscript",e.getElementsByTagName("head")[0].appendChild(t))}(self.document);var es=function(e){"use strict";const o={},c=e=>o[e],a=(e,t)=>{o[e]=t},s={},l=({id_event:e,callback:t})=>{if(!isFunction(t))return!1;const n=s[e],o=GlobalThings.get_UID(10);return n.listeners[o]={callback:t,remove:()=>{delete n.listeners[o]}},n.listeners[o].remove},r=({id_event:e,args:t})=>{const n=s[e];for(const o in n.listeners)try{n.listeners[o].callback(t)}catch(e){}},i=e=>{delete s[e]};var m={destroy:e=>{var t=c(e);if(!t)throw"This component does not exists";try{const n=t["element"];n.parentNode.removeChild(n)}catch(e){}e=e,delete o[e]},render:e=>{if(!c(e))throw"This component does not exists";const{data:t,template:n,element:o}=c(e);let s=n;for(const l in t)s=s.replaceAll(`{${l}}`,t[l]);o.innerHTML=s},setData:(e,t,n)=>{const o=c(e);if(!o)throw"This component does not exists";t=t||{},!1!==(n=n||{}).merge&&(t={...o.data,...t}),o.onChangeDataEvent&&o.onChangeDataEvent.dispatch({...t}),o.data=t},setTemplate:(e,t)=>{const n=c(e);if(!n)throw"This component does not exists";n.template=t||""},onChangeData:(e,t)=>{const n=c(e);if(!n)throw"This component does not exists";return n.onChangeDataEvent||(n.onChangeDataEvent=(t=>{if(s[t])throw"An event with this id already exists";return s[t]={listeners:{},remove:()=>i(t),dispatch:e=>r({id_event:t,args:e}),addListener:e=>l({id_event:t,callback:e})},s[t]})(e+"_onChangeDataEvent")),n.onChangeDataEvent.addListener(t)}};const d=e=>{return document.createElement(e)},_=function(e,t){e=e||"div";var{data:n,template:t}=t=t||{};const o=GlobalThings.get_UID(150),s=d(e);a(o,{uid:o,element:s,tag_name:e,data:{},template:""}),m.setTemplate(o,t),m.setData(o,n);const l=()=>{m.render(o)};return{element:s,appendTo:e=>{e.appendChild(s),l()},setData:e=>{m.setData(o,e),l()},setTemplate:e=>{m.setTemplate(o,e),l()},render:l,onChangeData:e=>{m.onChangeData(o,e)},destroy:()=>{m.destroy(o)}}},y={};const v=e=>{const t=document.querySelector("html");t.style.overflow="",y[e]._destroy()},h=e=>{const t=document.querySelector("html");t.style.overflow="",y[e].element.style.display="none","function"==typeof y[e].onclose&&y[e].onclose()},f=e=>{const t=document.querySelector("html");t.style.overflow="hidden",y[e].element.style.display=""},g="medium",C={small:"components_modal--content__small",small_600:"components_modal--content__small_600",medium:"components_modal--content__medium",medium_1200:"components_modal--content__medium_1200",medium_1300:"components_modal--content__medium_1300",large:"components_modal--content__large",complete:"components_modal--content__complete"},b="center",x={left:"components_modal--content__left",center:"components_modal--content__center",right:"components_modal--content__right"},T=`
			<div class="components_modal--header"> </div>
			<div class="components_modal--body"> </div>
			<div class="components_modal--footer"> </div>
		`,p=e=>{var{data:t,content:n,accept:o,cancel:e}=e=e||{},e=u({content:n,accept:o,cancel:e});const{appendTo:s,element:l,destroy:c}=_("div",{data:t,template:e});return l.className="components_alert",s(document.body),{acceptButton:l.querySelector('[btn-id="accept"]'),cancelButton:l.querySelector('[btn-id="cancel"]'),element:l,destroy:c}};const u=({content:e,cancel:t,accept:n})=>{return`
		<div class="components_alert--overlay"> </div>

		<div class="components_alert--content">
			<div class="components_alert--content--text">
				${e}
			</div>
			<div class="components_alert--content--controllers">
				${t?`
		<span class="components_alert--content--controllers--btn components_alert--content--controllers--btn__cancel" btn-id="cancel">${t}</span>
	`:""}
				<span class="components_alert--content--controllers--btn components_alert--content--controllers--btn__accept" btn-id="accept">${n=n||"Accept"}</span>
			</div>
		</div>
	`};const E={},w={duration:4e3,position:"bottom-left"},n={"top-left":"components_toast--container__top_left","top-right":"components_toast--container__top_right","bottom-left":"components_toast--container__bottom_left","bottom-right":"components_toast--container__bottom_right"},B={info:"components_toast--item__info",error:"components_toast--item__error",warning:"components_toast--item__warning",success:"components_toast--item__success"};const t=({text:e,type:t})=>{D();t=B[t]||B.success;const n=document.createElement("div");n.innerHTML=e||"",n.className=t+" components_toast--item",-1===w.position.indexOf("top")?E[w.position].appendChild(n):E[w.position].insertBefore(n,E[w.position].firstChild),n.onclick=()=>k(n),setTimeout(()=>k(n),w.duration)},k=e=>{e.classList.add("components_toast--item__clossing"),setTimeout(function(){e.parentNode.removeChild(e)},1e3)};const D=()=>{if(!E[w.position]){const e=document.createElement("div");e.className=n[w.position]+" components_toast--container",document.body.appendChild(e),E[w.position]=e}};function N(e){var{data:t,content:n,accept:e}=e;const{acceptButton:o,destroy:s}=p({data:t,content:n,accept:e});return new Promise(e=>{o.onclick=()=>{e(!0),s()}})}function $(e){var{data:t,content:n,accept:o,cancel:e}=e;const{acceptButton:s,cancelButton:l,destroy:c}=p({data:t,content:n,accept:o,cancel:e||"Cancel"});return new Promise(t=>{const e=e=>{t(e),c()};s.onclick=()=>e(!0),l.onclick=()=>e(!1)})}function L(e){var{data:t,title:n,inputs:o,accept:s,cancel:e}=e,o=(({title:e,inputs:t})=>{if(!t?.length)t=[{}];const n=t.reduce((e,t)=>{const{label:n,type:o}=t;const s=n?`<label>${n}</label>`:"";return e+`
			<div class="components_prompt--item">
				${s}
				<input class="components_prompt--input" type="${o||"text"}"/>
			</div>
		`},"");return`
		<div class="components_prompt--title">
			${e}
		</div>
		${n}

	`})({title:n,inputs:o});const{acceptButton:l,cancelButton:c,destroy:a,element:r}=p({data:t,content:o,accept:s,cancel:e||"Cancel"});return r.className+=" components_prompt",new Promise(n=>{const e=e=>{var t=r.querySelectorAll("input"),t=Array.from(t).map(e=>e.value);a(),e||n(null),n(t)};l.onclick=()=>e(!0),c.onclick=()=>e(!1)})}function A(e){const{items:t,onActive:n,darkMode:o}=e=e||{},l=_("div")["element"];l.setAttribute("tabindex","-1"),l.className="components_contextmenu",l.style.display="none",o&&l.classList.add("components_contextmenu__dark-mode"),document.body.appendChild(l),(t||[]).forEach(e=>{const t=_("a").element;t.className="components_contextmenu--item",t.innerHTML=`
			${e.text||""}
		`,l.appendChild(t),t.onclick=()=>{l.blur(),"function"==typeof n&&n(e)}}),l.addEventListener("focusout",()=>{l.style.display="none"});const c={appendTo:e=>{var s;c.element=e,[{parentElement:e,element:s}]=[{parentElement:e,element:l}],e.oncontextmenu=e=>{e.preventDefault(),s.style.display="",s.focus();var{pageY:t,pageX:n}=e,{offsetHeight:o,offsetWidth:e}=s;t+o>document.documentElement.clientHeight?(s.style.top="",s.style.bottom="0px"):(s.style.bottom="",s.style.top=t+"px"),n+e>document.documentElement.clientWidth?(s.style.left="",s.style.right="0px"):(s.style.right="",s.style.left=n+"px")}},destroy:()=>{c.element&&(c.element.oncontextmenu=null,l.parentNode.removeChild(l))}};return c}function M(e){let l="initial";const c=(e||{})["element"];c.classList.add("components_button");const a=(e=getComputedStyle(c)).backgroundColor,r=e.color;return{setState:e=>{const t=c.querySelector(".components_button--state");return t&&t.parentNode.removeChild(t),"initial"===(l=e)?([{element:n,elementColor:o,elementBgColor:s}]=[{element:c,elementColor:r,elementBgColor:a}],n.style.color=o,"initial"):("loading"===e?({element:e,elementColor:t,elementBgColor:n})=>{const o=document.createElement("span");return o.className="components_button--state components_button--state__loading fas fa-spinner",o.style.color=t,e.style.color=n,e.appendChild(o),"loading"}:({element:e,elementColor:t,elementBgColor:n})=>{const o=document.createElement("span");return o.className="components_button--state",o.style.color=t,e.style.color=n,e.appendChild(o),o})({element:c,elementColor:r,elementBgColor:a});var n,o,s},getState:()=>l}}function S({element:l,items:c}){if(Array.isArray(c)||(c=[]),!(l instanceof HTMLElement)&&"INPUT"!==l?.tagName)throw"element key must be an input.";const e=_("ul"),a=e.element;return e.appendTo(document.body),a.style.display="none",a.className="components_autocomplete",c=c.map(e=>{const t=document.createElement("li");return a.appendChild(t),t.innerHTML=e,t.style.display="none",t.onclick=()=>{l.value=e},{text:e,liElement:t}}),l.addEventListener("input",e=>{var{top:t,height:n,left:o,width:s}=l.getBoundingClientRect();a.style.top=`${t+n}px`,a.style.left=`${o}px`,a.style.width=`${s}px`,c.filter(e=>{var t=-1<e.text.toLowerCase().indexOf(l.value.toLowerCase());return e.liElement.style.display=t?"":"none",t}).length?a.style.display="":a.style.display="none"}),l.addEventListener("focusout",e=>{setTimeout(function(){a.style.display="none"},200)}),{destroy:e.destroy}}var q={create:function(e){var{data:t,template:n,id:o,type:s,position:l,all_height:c,top:a,close_on_overlay_click:r,onclose:e}=e=e||{};const i=_("div",{data:t,template:(({template:e,type:t,position:n,top:o,all_height:s})=>{e=e||"";const l=x[n]||x[b],c=C[t]||C[g],a=s?"components_modal--content__all_height":"";return`
				<div class="components_modal--overlay"></div>
				<div class="components_modal--display">
					<div class="components_modal--content ${c} ${l} ${a}" style="--top: ${o||"40px"};">
						${e||T}
					</div>
				</div>
			`})({template:n,type:s,position:l,all_height:c,top:a})}),m=i.appendTo,d=o||(()=>{var t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",n=t.length;let o="";for(let e=0;e<=100;e++)o+=t.charAt(Math.floor(Math.random()*n));return o})();if(i._destroy=i.destroy,y[d]={onclose:e,id:d,...i,open:()=>f(d),close:()=>h(d),destroy:()=>v(d)},y[d].element.className="components_modal",delete i.appendTo,y[d].element.style.display="none",y[d].element.id=o,m(document.body),!1!==r){const p=y[d].element.querySelector(".components_modal--display"),u=y[d].element.querySelector(".components_modal--content");u.onclick=e=>e.stopPropagation(),p.onclick=e=>h(d)}return y[d]},destroyByID:v,closeByID:h,openByID:f},P={success:e=>{t({text:e,type:"success"})},warning:e=>{t({text:e,type:"warning"})},error:e=>{t({text:e,type:"error"})},info:e=>{t({text:e,type:"info"})},set:({position:e,duration:t})=>{e&&(w.position=n[e]?e:w.position),Number(t)&&0<t&&(w.duration=t)}},H={Modal:q,Alert:N,Confirm:$,Prompt:L,Toast:P,Button:M,ContextMenu:A,AutoComplete:S};return e.Alert=N,e.AutoComplete=S,e.Button=M,e.Confirm=$,e.ContextMenu=A,e.Modal=q,e.Prompt=L,e.Toast=P,e.default=H,Object.defineProperty(e,"__esModule",{value:!0}),e}({});
