var es=function(t){"use strict";const o={},a=t=>o[t],l=(t,e)=>{o[t]=e},c={},s=({id_event:t,callback:e})=>{if(!isFunction(e))return!1;const n=c[t],o=GlobalThings.get_UID(10);return n.listeners[o]={callback:e,remove:()=>{delete n.listeners[o]}},n.listeners[o].remove},r=({id_event:t,args:e})=>{const n=c[t];for(const o in n.listeners)try{n.listeners[o].callback(e)}catch(t){}},i=t=>{delete c[t]};var m={destroy:t=>{var e=a(t);if(!e)throw"This component does not exists";try{const n=e["element"];n.parentNode.removeChild(n)}catch(t){}t=t,delete o[t]},render:t=>{if(!a(t))throw"This component does not exists";const{data:e,template:n,element:o}=a(t);let c=n;for(const s in e)c=c.replaceAll(`{${s}}`,e[s]);o.innerHTML=c},setData:(t,e,n)=>{const o=a(t);if(!o)throw"This component does not exists";e=e||{},!1!==(n=n||{}).merge&&(e={...o.data,...e}),o.onChangeDataEvent&&o.onChangeDataEvent.dispatch({...e}),o.data=e},setTemplate:(t,e)=>{const n=a(t);if(!n)throw"This component does not exists";n.template=e||""},onChangeData:(t,e)=>{const n=a(t);if(!n)throw"This component does not exists";return n.onChangeDataEvent||(n.onChangeDataEvent=(e=>{if(c[e])throw"An event with this id already exists";return c[e]={listeners:{},remove:()=>i(e),dispatch:t=>r({id_event:e,args:t}),addListener:t=>s({id_event:e,callback:t})},c[e]})(t+"_onChangeDataEvent")),n.onChangeDataEvent.addListener(e)}};const d=t=>{return document.createElement(t)},u=function(t,e){t=t||"div";var{data:n,template:e}=e=e||{};const o=GlobalThings.get_UID(150),c=d(t);l(o,{uid:o,element:c,tag_name:t,data:{},template:""}),m.setTemplate(o,e),m.setData(o,n);const s=()=>{m.render(o)};return{element:c,appendTo:t=>{t.appendChild(c),s()},setData:t=>{m.setData(o,t),s()},setTemplate:t=>{m.setTemplate(o,t),s()},render:s,onChangeData:t=>{m.onChangeData(o,t)},destroy:()=>{m.destroy(o)}}},y={};const v=t=>{const e=document.querySelector("html");e.style.overflow="",y[t]._destroy()},h=t=>{const e=document.querySelector("html");e.style.overflow="",y[t].element.style.display="none","function"==typeof y[t].onclose&&y[t].onclose()},f=t=>{const e=document.querySelector("html");e.style.overflow="hidden",y[t].element.style.display=""},g="medium",b={small:"components_modal--content__small",small_600:"components_modal--content__small_600",medium:"components_modal--content__medium",medium_1200:"components_modal--content__medium_1200",medium_1300:"components_modal--content__medium_1300",large:"components_modal--content__large",complete:"components_modal--content__complete"},C="center",x={left:"components_modal--content__left",center:"components_modal--content__center",right:"components_modal--content__right"},T=`
			<div class="components_modal--header"> </div>
			<div class="components_modal--body"> </div>
			<div class="components_modal--footer"> </div>
		`,p=t=>{var{data:e,content:n,accept:o,cancel:t}=t=t||{},t=_({content:n,accept:o,cancel:t});const{appendTo:c,element:s,destroy:a}=u("div",{data:e,template:t});return s.className="components_alert",c(document.body),{acceptButton:s.querySelector('[btn-id="accept"]'),cancelButton:s.querySelector('[btn-id="cancel"]'),element:s,destroy:a}};const _=({content:t,cancel:e,accept:n})=>{return`
		<div class="components_alert--overlay"> </div>

		<div class="components_alert--content">
			<div class="components_alert--content--text">
				${t}
			</div>
			<div class="components_alert--content--controllers">
				${e?`
		<span class="components_alert--content--controllers--btn components_alert--content--controllers--btn__cancel" btn-id="cancel">${e}</span>
	`:""}
				<span class="components_alert--content--controllers--btn components_alert--content--controllers--btn__accept" btn-id="accept">${n=n||"Accept"}</span>
			</div>
		</div>
	`};const D={},B={duration:4e3,position:"bottom-left"},n={"top-left":"components_toast--container__top_left","top-right":"components_toast--container__top_right","bottom-left":"components_toast--container__bottom_left","bottom-right":"components_toast--container__bottom_right"},k={info:"components_toast--item__info",error:"components_toast--item__error",warning:"components_toast--item__warning",success:"components_toast--item__success"};const e=({text:t,type:e})=>{E();e=k[e]||k.success;const n=document.createElement("div");n.innerHTML=t||"",n.className=e+" components_toast--item",-1===B.position.indexOf("top")?D[B.position].appendChild(n):D[B.position].insertBefore(n,D[B.position].firstChild),n.onclick=()=>w(n),setTimeout(()=>w(n),B.duration)},w=t=>{t.classList.add("components_toast--item__clossing"),setTimeout(function(){t.parentNode.removeChild(t)},1e3)};const E=()=>{if(!D[B.position]){const t=document.createElement("div");t.className=n[B.position]+" components_toast--container",document.body.appendChild(t),D[B.position]=t}};function $(t){var{data:e,content:n,accept:t}=t;const{acceptButton:o,destroy:c}=p({data:e,content:n,accept:t});return new Promise(t=>{o.onclick=()=>{t(!0),c()}})}function N(t){var{data:e,content:n,accept:o,cancel:t}=t;const{acceptButton:c,cancelButton:s,destroy:a}=p({data:e,content:n,accept:o,cancel:t||"Cancel"});return new Promise(e=>{const t=t=>{e(t),a()};c.onclick=()=>t(!0),s.onclick=()=>t(!1)})}function S(t){var{data:e,title:n,inputs:o,accept:c,cancel:t}=t,o=(({title:t,inputs:e})=>{if(!e?.length)e=[{}];const n=e.reduce((t,e)=>{const{label:n,type:o}=e;const c=n?`<label>${n}</label>`:"";return t+`
			<div class="components_prompt--item">
				${c}
				<input class="components_prompt--input" type="${o||"text"}"/>
			</div>
		`},"");return`
		<div class="components_prompt--title">
			${t}
		</div>
		${n}

	`})({title:n,inputs:o});const{acceptButton:s,cancelButton:a,destroy:l,element:r}=p({data:e,content:o,accept:c,cancel:t||"Cancel"});return r.className+=" components_prompt",new Promise(n=>{const t=t=>{var e=r.querySelectorAll("input"),e=Array.from(e).map(t=>t.value);l(),t||n(null),n(e)};s.onclick=()=>t(!0),a.onclick=()=>t(!1)})}function M(t){const{items:e,onActive:n,darkMode:o}=t=t||{},s=u("div")["element"];s.setAttribute("tabindex","-1"),s.className="components_contextmenu",s.style.display="none",o&&s.classList.add("components_contextmenu__dark-mode"),document.body.appendChild(s),(e||[]).forEach(t=>{const e=u("a").element;e.className="components_contextmenu--item",e.innerHTML=`
			${t.text||""}
		`,s.appendChild(e),e.onclick=()=>{s.blur(),"function"==typeof n&&n(t)}}),s.addEventListener("focusout",()=>{s.style.display="none"});const a={appendTo:t=>{var c;a.element=t,[{parentElement:t,element:c}]=[{parentElement:t,element:s}],t.oncontextmenu=t=>{t.preventDefault(),c.style.display="",c.focus();var{pageY:e,pageX:n}=t,{offsetHeight:o,offsetWidth:t}=c;e+o>document.documentElement.clientHeight?(c.style.top="",c.style.bottom="0px"):(c.style.bottom="",c.style.top=e+"px"),n+t>document.documentElement.clientWidth?(c.style.left="",c.style.right="0px"):(c.style.right="",c.style.left=n+"px")}},destroy:()=>{a.element&&(a.element.oncontextmenu=null,s.parentNode.removeChild(s))}};return a}function A(t){let s="initial";const a=(t||{})["element"];a.classList.add("components_button");const l=(t=getComputedStyle(a)).backgroundColor,r=t.color;return{setState:t=>{const e=a.querySelector(".components_button--state");return e&&e.parentNode.removeChild(e),"initial"===(s=t)?([{element:n,elementColor:o,elementBgColor:c}]=[{element:a,elementColor:r,elementBgColor:l}],n.style.color=o,"initial"):("loading"===t?({element:t,elementColor:e,elementBgColor:n})=>{const o=document.createElement("span");return o.className="components_button--state components_button--state__loading fas fa-spinner",o.style.color=e,t.style.color=n,t.appendChild(o),"loading"}:({element:t,elementColor:e,elementBgColor:n})=>{const o=document.createElement("span");return o.className="components_button--state",o.style.color=e,t.style.color=n,t.appendChild(o),o})({element:a,elementColor:r,elementBgColor:l});var n,o,c},getState:()=>s}}var q={create:function(t){var{data:e,template:n,id:o,type:c,position:s,all_height:a,top:l,close_on_overlay_click:r,onclose:t}=t=t||{};const i=u("div",{data:e,template:(({template:t,type:e,position:n,top:o,all_height:c})=>{t=t||"";const s=x[n]||x[C],a=b[e]||b[g],l=c?"components_modal--content__all_height":"";return`
				<div class="components_modal--overlay"></div>
				<div class="components_modal--display">
					<div class="components_modal--content ${a} ${s} ${l}" style="--top: ${o||"40px"};">
						${t||T}
					</div>
				</div>
			`})({template:n,type:c,position:s,all_height:a,top:l})}),m=i.appendTo,d=o||(()=>{var e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",n=e.length;let o="";for(let t=0;t<=100;t++)o+=e.charAt(Math.floor(Math.random()*n));return o})();if(i._destroy=i.destroy,y[d]={onclose:t,id:d,...i,open:()=>f(d),close:()=>h(d),destroy:()=>v(d)},y[d].element.className="components_modal",delete i.appendTo,y[d].element.style.display="none",y[d].element.id=o,m(document.body),!1!==r){const p=y[d].element.querySelector(".components_modal--display"),_=y[d].element.querySelector(".components_modal--content");_.onclick=t=>t.stopPropagation(),p.onclick=t=>h(d)}return y[d]},destroyByID:v,closeByID:h,openByID:f},L={success:t=>{e({text:t,type:"success"})},warning:t=>{e({text:t,type:"warning"})},error:t=>{e({text:t,type:"error"})},info:t=>{e({text:t,type:"info"})},set:({position:t,duration:e})=>{t&&(B.position=n[t]?t:B.position),Number(e)&&0<e&&(B.duration=e)}},P={Modal:q,Alert:$,Confirm:N,Prompt:S,Toast:L,Button:A,ContextMenu:M};return t.Alert=$,t.Button=A,t.Confirm=N,t.ContextMenu=M,t.Modal=q,t.Prompt=S,t.Toast=L,t.default=P,Object.defineProperty(t,"__esModule",{value:!0}),t}({});
